package GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author James Baxter
 */
public class VOIPGUI extends javax.swing.JFrame {

    public VOIPservice voip;

    public VOIPGUI() {
        initComponents();
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        SemesterSelectCard = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        hostSelection = new javax.swing.JTextField();
        fileInfoText1 = new javax.swing.JLabel();
        fileInfoText2 = new javax.swing.JLabel();
        fileInfoText3 = new javax.swing.JLabel();
        socketSelection = new javax.swing.JComboBox<>();
        fileInfoText4 = new javax.swing.JLabel();
        bitrateselection = new javax.swing.JComboBox<>();
        portSelection = new javax.swing.JFormattedTextField();
        bottomPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        welcomeLabelSemesterSelect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        SemesterSelectCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyPanel.setBackground(new java.awt.Color(44, 151, 223));

        hostSelection.setBackground(new java.awt.Color(42, 128, 185));
        hostSelection.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hostSelection.setForeground(new java.awt.Color(255, 255, 255));
        hostSelection.setText("LOCALHOST");
        hostSelection.setBorder(null);
        hostSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostSelectionActionPerformed(evt);
            }
        });

        fileInfoText1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        fileInfoText1.setForeground(new java.awt.Color(255, 255, 255));
        fileInfoText1.setText("HostName:");

        fileInfoText2.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        fileInfoText2.setForeground(new java.awt.Color(255, 255, 255));
        fileInfoText2.setText("Port:");

        fileInfoText3.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        fileInfoText3.setForeground(new java.awt.Color(255, 255, 255));
        fileInfoText3.setText("Socket:");

        socketSelection.setBackground(new java.awt.Color(42, 128, 185));
        socketSelection.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        socketSelection.setForeground(new java.awt.Color(255, 255, 255));
        socketSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Socket 1", "Socket 2", "Socket 3", "Socket 4" }));
        socketSelection.setBorder(null);

        fileInfoText4.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        fileInfoText4.setForeground(new java.awt.Color(255, 255, 255));
        fileInfoText4.setText("Recording bitrate:");

        bitrateselection.setBackground(new java.awt.Color(42, 128, 185));
        bitrateselection.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bitrateselection.setForeground(new java.awt.Color(255, 255, 255));
        bitrateselection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard( 8kHz , 16bit, 128kbps)", "Low (4kHz,16bit, 64kbps)", "High (16kHz,16bit, 256kbps)" }));
        bitrateselection.setBorder(null);

        portSelection.setBackground(new java.awt.Color(42, 128, 185));
        portSelection.setBorder(null);
        portSelection.setForeground(new java.awt.Color(255, 255, 255));
        portSelection.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        portSelection.setText("5555");
        portSelection.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(fileInfoText1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hostSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                        .addComponent(fileInfoText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                        .addComponent(fileInfoText3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(socketSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(fileInfoText4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bitrateselection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileInfoText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hostSelection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileInfoText2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(portSelection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fileInfoText3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(socketSelection))
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileInfoText4)
                    .addComponent(bitrateselection, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        SemesterSelectCard.add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 980, 360));

        bottomPanel.setBackground(new java.awt.Color(42, 128, 185));

        jButton2.setBackground(new java.awt.Color(42, 128, 185));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startcall.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setMaximumSize(new java.awt.Dimension(999, 999));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(860, 860, 860))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        SemesterSelectCard.add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 488, 980, -1));

        topPanel.setBackground(new java.awt.Color(42, 128, 185));

        welcomeLabelSemesterSelect.setFont(new java.awt.Font("Segoe UI Light", 1, 90)); // NOI18N
        welcomeLabelSemesterSelect.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLabelSemesterSelect.setText("VOIP Client");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabelSemesterSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabelSemesterSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        SemesterSelectCard.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 130));

        mainPanel.add(SemesterSelectCard, "SemesterSelectCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hostSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostSelectionActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int bitrate = bitrateselection.getSelectedIndex();
        int socket = socketSelection.getSelectedIndex();
        try {
            portSelection.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(VOIPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        int port = Integer.parseInt(portSelection.getValue().toString());
        String hostname = hostSelection.getText();
        voip = new VOIPservice(hostname,port,socket,bitrate);
        new CallGUI(voip,this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudyDashboardBetaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudyDashboardBetaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudyDashboardBetaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudyDashboardBetaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOIPGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SemesterSelectCard;
    private javax.swing.JComboBox<String> bitrateselection;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JLabel fileInfoText1;
    private javax.swing.JLabel fileInfoText2;
    private javax.swing.JLabel fileInfoText3;
    private javax.swing.JLabel fileInfoText4;
    private javax.swing.JTextField hostSelection;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JFormattedTextField portSelection;
    private javax.swing.JComboBox<String> socketSelection;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel welcomeLabelSemesterSelect;
    // End of variables declaration//GEN-END:variables

    

    private void switchCard(JPanel target, String cardName) {
        CardLayout card = (CardLayout) target.getLayout();
        card.show(target, cardName);
    }


}
